aligned

diff --git a/releasescripts/tagRelCan b/releasescripts/tagRelCan
--- a/releasescripts/tagRelCan
+++ b/releasescripts/tagRelCan
@@ -45,69 +45,68 @@ fi
 
 cd .repo/manifests
 if [ $? -eq 0 ]; then
-  	# Checkout releasebranch for all components and manifest
+   # Checkout releasebranch for all components and manifest
    repo forall  $(repo forall -c 'echo $REPO_PROJECT' | grep -v bsb002-zigbee) -c 'pwd; git checkout '$1'; git pull'
-	if [ $? -eq 0 ]; then
-		 echo "------Checked out branch $1 at all components------"
-	else
-		 echo "------Failed to checkout branch $1 at one of the components------"
-		 exit 1
-	fi
+   if [ $? -eq 0 ]; then
+      echo "------Checked out branch $1 at all components------"
+   else
+      echo "------Failed to checkout branch $1 at one of the components------"
+      exit 1
+   fi
 
-	git checkout $1; git pull
-	if [ $? -eq 0 ]; then
-		echo "------Checked out branch $1 at manifest------"
-	else
-		echo "------Failed to checkout branch $1 at manifest------"
-		exit 1
-	fi
+   git checkout $1; git pull
+   if [ $? -eq 0 ]; then
+      echo "------Checked out branch $1 at manifest------"
+   else
+      echo "------Failed to checkout branch $1 at manifest------"
+      exit 1
+   fi
 
-	# First tag all components at the release branch 
-	repo forall  $(repo forall -c 'echo $REPO_PROJECT' | grep -v bsb002-zigbee) -c 'pwd; git tag '$2''
-	if [ $? -eq 0 ]; then 
-		echo "------ Tagged branch $1 with tag : $2 at each component------"
-	else
-		echo "------ Failed to tag branch $1 at components------"
-	   exit 1
-	fi
+   # First tag all components at the release branch 
+   repo forall  $(repo forall -c 'echo $REPO_PROJECT' | grep -v bsb002-zigbee) -c 'pwd; git tag '$2''
+   if [ $? -eq 0 ]; then 
+      echo "------ Tagged branch $1 with tag : $2 at each component------"
+   else
+      echo "------ Failed to tag branch $1 at components------"
+      exit 1
+   fi
 
-	# Update the manifest at the release branch so all components track the tag
-	while read line; do
-		echo $line | grep -q 'refs/tags/' 
-	   if [ ${PIPESTATUS[1]} -eq 1 ]; then
-			echo $line | sed 's@\(.*revision=refs/tags/"\)[^ ]*\("\)@\1'$2'\2@'
-	   else 
-		   echo $line
-	   fi
-	done < default.xml > temp.xml && mv temp.xml default.xml
-	echo "Manifest :all components track : '$2'"
-	git commit -am "All components track : '$2'"
+   # Update the manifest at the release branch so all components track the tag
+   while read line; do
+      echo $line | grep -q 'refs/tags/' 
+      if [ ${PIPESTATUS[1]} -eq 1 ]; then
+         echo $line | sed 's@\(.*revision=refs/tags/"\)[^ ]*\("\)@\1'$2'\2@'
+      else 
+         echo $line
+      fi
+   done < default.xml > temp.xml && mv temp.xml default.xml
+   echo "Manifest :all components track : '$2'"
+   git commit -am "All components track : '$2'"
 
-	# Next also tag the manifest
-   git tag '$2'
+   # Next also tag the manifest
+   git tag $2
 
-	#push all changes to origin
-	repo forall  $(repo forall -c 'echo $REPO_PROJECT' | grep -v bsb002-zigbee) -c 'pwd; git push origin '$1''
-	if [ $? -eq 0 ]; then 
-		echo "------Pushed $1 to origin for all components -------"
-	else
-		echo "----- Failed to push $1 to origin for all components ------"
-	     exit 1
-	fi
+   #push all changes to origin
+   repo forall  $(repo forall -c 'echo $REPO_PROJECT' | grep -v bsb002-zigbee) -c 'pwd; git push origin '$1''
+   if [ $? -eq 0 ]; then 
+      echo "------Pushed $1 to origin for all components -------"
+   else
+      echo "----- Failed to push $1 to origin for all components ------"
+      exit 1
+   fi
 
-	#push the new tag of all components to origin
-	repo forall  $(repo forall -c 'echo $REPO_PROJECT' | grep -v bsb002-zigbee) -c 'pwd; git push origin '$2''
-	if [ $? -eq 0 ]; then 
-        echo "------ Pushed tag $2 to origin for all components ------"
-    else
-        echo "------ Failed to push tag $2 to origin for all components-------"
-        exit 1
-    fi
+   #push the new tag of all components to origin
+   repo forall  $(repo forall -c 'echo $REPO_PROJECT' | grep -v bsb002-zigbee) -c 'pwd; git push origin '$2''
+   if [ $? -eq 0 ]; then 
+      echo "------ Pushed tag $2 to origin for all components ------"
+   else
+      echo "------ Failed to push tag $2 to origin for all components-------"
+      exit 1
+   fi
 
-	# Push the manifest and its tag to origin (a new promotion build is started)
-    git push origin $1
-    git push origin $2
+   #Push the manifest and its tag to origin (a new promotion build is started)
+   git push origin $1
+   git push origin $2
 else
-	echo "Could not navigate to the manifest directory...please run this tool in the root directory of your project"
+   echo "Could not navigate to the manifest directory...please run this tool in the root directory of your project"
 fi
-
